export default {
    // LOGIN 
    GET_USER: 'GET_USER',
    GETTING_USER: 'GETTING_USER',

    // CONDICIONES
    GET_CONDICIONES: 'GET_CONDICIONES',
    GETTING_CONDICIONES: 'GETTING_CONDICIONES',

    
    // FILTROS
    FILTROS: 'FILTROS',
    GETTING_FILTROS:'GETTING_FILTROS',

    GETTING_PORCENTAJES: 'GETTING_PORCENTAJES',
    GET_PORCENTAJES: 'GET_PORCENTAJES',
    // ALERTA
    ALERTA: 'ALERTA',
    TYPE_ALERTA: 'TYPE_ALERTA',

    // PROVEEDORES
    GET_PROVIDERS: 'GET_PROVIDERS',
    GETTING_PROVIDERS: 'GETTING_PROVIDERS',
    GET_PROVIDER: 'GET_PROVIDER',
    GETTING_PROVIDER: 'GETTING_PROVIDER',
    
    //  PRIMAS
    GET_PRIMAS: 'GET_PRIMAS',
    GETTING_PRIMAS: 'GETTING_PRIMAS',
    GET_PRIMA: 'GET_PRIMA',
    GETTING_PRIMA: 'GETTING_PRIMA',

    // TERMINADO
    GET_PRODUCTOS: 'GET_PRODUCTOS',
    GETTING_PRODUCTOS: 'GETTING_PRODUCTOS',
    GET_PRODUCTO: 'GET_PRODUCTO',
    GETTING_PRODUCTO: 'GETTING_PRODUCTO',


    // KITS
    GET_KITS: 'GET_KITS',
    GETTING_KITS: 'GETTING_KITS',
    GET_KIT: 'GET_KIT',
    GETTING_KIT: 'GETTING_KIT',
    GET_SUPERKITS: 'GET_SUPERKITS',
    GETTING_SUPERKITS: 'GETTING_SUPERKITS',
    GET_SUPERKIT: 'GET_SUPERKIT',
    GETTING_SUPERKIT: 'GETTING_SUPERKIT', 
        
    // KITS
    GET_COTIZACIONES: 'GET_COTIZACIONES',
    GETTING_COTIZACIONES: 'GETTING_COTIZACIONES',
    GET_COTIZACION: 'GET_COTIZACION',
    GETTING_COTIZACION: 'GETTING_COTIZACION',

    // REQUISICIONES
    GET_REQUISICIONS: 'GET_REQUISICIONS',
    GETTING_REQUISICIONS: 'GETTING_REQUISICIONS',
    GET_REQUISICION: 'GET_REQUISICION',
    GETTING_REQUISICION: 'GETTING_REQUISICION',
    GET_IDS: 'GET_IDS',
    LOADING_IDS: 'LOADING_IDS',
    GET_MATERIA_PRIMA_REQUISICION: 'GET_MATERIA_PRIMA_REQUISICION',
    GET_PROYECTOS_REQUISICION: 'GET_PROYECTOS_REQUISICION',
    GET_KITS_REQUISICION: 'GET_KITS_REQUISICION', 
    GET_UNA_MATERIA_PRIMA_REQUISICION: 'GET_UNA_MATERIA_PRIMA_REQUISICION', // VISUALIZAR UN ITEM
    GET_COMPRAS_COTIZACIONES: 'GET_COMPRAS_COTIZACIONES',
    GETTING_UNA_MATERIA_PRIMA_REQUISICION: 'GETTING_UNA_MATERIA_PRIMA_REQUISICION',
    GET_COMPRAS: 'GET_COMPRAS',
    GETTING_COMPRAS: 'GETTING_COMPRAS',
    // CLIENTES
    GET_CLIENTS: 'GET_CLIENTS',
    GETTING_CLIENTS: 'GETTING_CLIENTS',
    GET_CLIENT: 'GET_CLIENT',
    GETTING_CLIENT: 'GETTING_CLIENT',


    // ADMINISTRACIÓN
    GET_COTIZACIONES_PRODUCCION: 'GET_COTIZACIONES_PRODUCCION',
    GETTING_COTIZACIONES_PRODUCCION: 'GETTING_COTIZACIONES_PRODUCCION',
    GET_GRAPH_PRODUCTO: 'GET_GRAPH_PRODUCTO',
    GETTING_GRAPH_PRODUCTO: 'GETTING_GRAPH_PRODUCTO',
    GET_PRODUCCION: 'GET_PRODUCCION',
    GETTING_PRODUCCION: 'GETTING_PRODUCCION',
    GET_GRAPH_KITS: 'GET_GRAPH_KITS',
    GETTING_GRAPH_KITS: 'GETTING_GRAPH_KITS',
    GET_COTIZACIONES_ADMIN: 'GET_COTIZACIONES_ADMIN',
    GETTING_COTIZACIONES_ADMIN: 'GETTING_COTIZACIONES_ADMIN',
    GET_ORDENES_COMPRAS: 'GET_ORDENES_COMPRAS',
    GETTING_ORDENES_COMPRAS: 'GETTING_ORDENES_COMPRAS', 
    GET_ORDEN_COMPRAS: 'GET_ORDEN_COMPRAS',
    GETTING_ORDEN_COMPRAS: 'GETTING_ORDEN_COMPRAS', 

    // NOTIFICACIONES
    GET_REQUERIMIENTOS: 'GET_REQUERIMIENTOS',
    GETTING_REQUERIMIENTOS: 'GETTING_REQUERIMIENTOS',

    GET_REQUERIMIENTO: 'GET_REQUERIMIENTO',
    GETTING_REQUERIMIENTO: 'GETTING_REQUERIMIENTO',


    // ALMACEN
    GET_CABECERAS: 'GET_CABECERAS',
    GETTING_CABECERAS: 'GETTING_CABECERAS',
    GET_PRODUCTOS_BODEGA: 'GET_PRODUCTOS_BODEGA',
    GETTING_PRODUCTOS_BODEGA: 'GETTING_PRODUCTOS_BODEGA',
    GET_MOVIMIENTOS_BODEGA: 'GET_MOVIMIENTOS_BODEGA',
    GETTING_MOVIMIENTOS_BODEGA: 'GETTING_MOVIMIENTOS_BODEGA',

    // ITEM ALMACEN
    GET_ITEM: 'GET_ITEM',
    GETTING_ITEM: 'GETTING_ITEM',
    GET_PROJECTS: 'GET_PROJECTS',
    GETTING_PROJECTS: 'GETTING_PROJECTS',
    GETTING_ORDENES: 'GETTING_ORDENES',
    GET_ORDENES: 'GET_ORDENES',
    GET_PROJECT: 'GET_PROJECT',
    GETTING_PROJECT: 'GETTING_PROJECT',
    GET_ITEM_TO_PROJECT: 'GET_ITEM_TO_PROJECT',
    GETTING_ITEM_TO_PROJECT: 'GETTING_ITEM_TO_PROJECT',

    GET_ITEM_BODEGA: 'GET_ITEM_BODEGA',
    GETTING_ITEM_BODEGA: 'GETTING_ITEM_BODEGA',
    // PARA COTIZAR
    GET_MATERIAS_IDS: 'GET_MATERIAS_IDS',
    GET_COTIZACION_FAST: 'GET_COTIZACION_FAST',
    GETTING_COTIZACION_FAST: 'GETTING_COTIZACION_FAST', 
    GET_ITEMS_COTIZACION: 'GET_ITEMS_COTIZACION', // OBTENER ITEMS PARA COTIZACIÓN
    CLEAN_ITEMS_COTIZACION: 'CLEAN_ITEMS_COTIZACION',
    GET_PROVEEDORES_ARRAY: 'GET_PROVEEDORES_ARRAY',
    GETTING_PRODUCTION_ITEMS: 'GETTING_PRODUCTION_ITEMS',
    GET_PRODUCTION_ITEMS: 'GET_PRODUCTION_ITEMS',
    GETTING_PRODUCTION_ITEM: 'GETTING_PRODUCTION_ITEM',
    GET_PRODUCTION_ITEM: 'GET_PRODUCTION_ITEM',
    GET_ITEM_ELEMENTO: 'GET_ITEM_ELEMENTO',
    GETTING_ITEM_ELEMENTO: 'GETTING_ITEM_ELEMENTO',
}
