export default {
    // LOGIN 
    GET_USER: 'GET_USER',
    GETTING_USER: 'GETTING_USER',

    // FILTROS
    FILTROS: 'FILTROS',
    GETTING_FILTROS:'GETTING_FILTROS',
    // ALERTA
    ALERTA: 'ALERTA',
    TYPE_ALERTA: 'TYPE_ALERTA',

    // PROVEEDORES
    GET_PROVIDERS: 'GET_PROVIDERS',
    GETTING_PROVIDERS: 'GETTING_PROVIDERS',
    GET_PROVIDER: 'GET_PROVIDER',
    GETTING_PROVIDER: 'GETTING_PROVIDER',

    //  PRIMAS
    GET_PRIMAS: 'GET_PRIMAS',
    GETTING_PRIMAS: 'GETTING_PRIMAS',
    GET_PRIMA: 'GET_PRIMA',
    GETTING_PRIMA: 'GETTING_PRIMA',


    // KITS
    GET_KITS: 'GET_KITS',
    GETTING_KITS: 'GETTING_KITS',
    GET_KIT: 'GET_KIT',
    GETTING_KIT: 'GETTING_KIT',
        
    // KITS
    GET_COTIZACIONES: 'GET_COTIZACIONES',
    GETTING_COTIZACIONES: 'GETTING_COTIZACIONES',
    GET_COTIZACION: 'GET_COTIZACION',
    GETTING_COTIZACION: 'GETTING_COTIZACION',

    // REQUISICIONES
    GET_REQUISICIONS: 'GET_REQUISICIONS',
    GETTING_REQUISICIONS: 'GETTING_REQUISICIONS',
    GET_REQUISICION: 'GET_REQUISICION',
    GETTING_REQUISICION: 'GETTING_REQUISICION'
}
