export default {
    // LOGIN 
    GET_USER: 'GET_USER',
    GETTING_USER: 'GETTING_USER',

    // CONDICIONES
    GET_CONDICIONES: 'GET_CONDICIONES',
    GETTING_CONDICIONES: 'GETTING_CONDICIONES',

    
    // FILTROS
    FILTROS: 'FILTROS',
    GETTING_FILTROS:'GETTING_FILTROS',

    GETTING_PORCENTAJES: 'GETTING_PORCENTAJES',
    GET_PORCENTAJES: 'GET_PORCENTAJES',
    // ALERTA
    ALERTA: 'ALERTA',
    TYPE_ALERTA: 'TYPE_ALERTA',

    // PROVEEDORES
    GET_PROVIDERS: 'GET_PROVIDERS',
    GETTING_PROVIDERS: 'GETTING_PROVIDERS',
    GET_PROVIDER: 'GET_PROVIDER',
    GETTING_PROVIDER: 'GETTING_PROVIDER',
    
    //  PRIMAS
    GET_PRIMAS: 'GET_PRIMAS',
    GETTING_PRIMAS: 'GETTING_PRIMAS',
    GET_PRIMA: 'GET_PRIMA',
    GETTING_PRIMA: 'GETTING_PRIMA',

    // TERMINADO
    GET_PRODUCTOS: 'GET_PRODUCTOS',
    GETTING_PRODUCTOS: 'GETTING_PRODUCTOS',
    GET_PRODUCTO: 'GET_PRODUCTO',
    GETTING_PRODUCTO: 'GETTING_PRODUCTO',


    // KITS
    GET_KITS: 'GET_KITS',
    GETTING_KITS: 'GETTING_KITS',
    GET_KIT: 'GET_KIT',
    GETTING_KIT: 'GETTING_KIT',
    GET_SUPERKITS: 'GET_SUPERKITS',
    GETTING_SUPERKITS: 'GETTING_SUPERKITS',
    GET_SUPERKIT: 'GET_SUPERKIT',
    GETTING_SUPERKIT: 'GETTING_SUPERKIT', 
        
    // KITS
    GET_COTIZACIONES: 'GET_COTIZACIONES',
    GETTING_COTIZACIONES: 'GETTING_COTIZACIONES',
    GET_COTIZACION: 'GET_COTIZACION',
    GETTING_COTIZACION: 'GETTING_COTIZACION',

    // REQUISICIONES
    GET_REQUISICIONS: 'GET_REQUISICIONS',
    GETTING_REQUISICIONS: 'GETTING_REQUISICIONS',
    GET_REQUISICION: 'GET_REQUISICION',
    GETTING_REQUISICION: 'GETTING_REQUISICION',

    // CLIENTES
    GET_CLIENTS: 'GET_CLIENTS',
    GETTING_CLIENTS: 'GETTING_CLIENTS',
    GET_CLIENT: 'GET_CLIENT',
    GETTING_CLIENT: 'GETTING_CLIENT',


    // ADMINISTRACIÓN
    GET_GRAPH_PRODUCTO: 'GET_GRAPH_PRODUCTO',
    GETTING_GRAPH_PRODUCTO: 'GETTING_GRAPH_PRODUCTO',
    GET_PRODUCCION: 'GET_PRODUCCION',
    GETTING_PRODUCCION: 'GETTING_PRODUCCION',
    GET_GRAPH_KITS: 'GET_GRAPH_KITS',
    GETTING_GRAPH_KITS: 'GETTING_GRAPH_KITS',
    GET_COTIZACIONES_ADMIN: 'GET_COTIZACIONES_ADMIN',
    GETTING_COTIZACIONES_ADMIN: 'GETTING_COTIZACIONES_ADMIN'

}
